name: Deploy React + Node (Self Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          cd /var/www/html/React
          git pull origin main

      # ---------- FRONTEND ----------
      - name: Build Frontend
        run: |
          cd /var/www/html/React/frontend
          npm install
          npm run build

      # ---------- BACKEND ----------
      - name: Install Backend Dependencies
        run: |
          cd /var/www/html/React/backend
          npm install

      - name: Restart PM2
        run: |
          cd /var/www/html/React/backend
          sudo pm2 restart server
          sudo pm2 save
